### ISSUE TITLE
Use https://github.com/magicaljellybeans/mkdocs_schema_reader ?

### ISSUE THREAD

**Issue by pengolod** [packwiz/packwiz-website#4]
This is nearly perfect, except for the part where it's not very readable/usable 😅

![image](https://user-images.githubusercontent.com/80605795/135362892-c9558cc4-b31a-4d7a-ae03-bcd0f36ac5bc.png)

not bad though

**Comment by pengolod** [comment]
Just a `pip3 install mkdocs-schema-reader` and adding

```yaml
plugins:
  - search
  - schema_reader:
      include:
        - "./packwiz-spec/schemas"
```
to `mkdocs-base.yaml
